### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by hvassbotn**

### CODE REVIEW

**Comment by jpluimers** [comment]
Note the Delphi 2007 compiler throws this in `MPlusTestsUnit`:

```
[DCC Error] MPlusTestsUnit.pas(182): E2029 $IFEND expected but $ENDIF found
```

I'll merge and then commit a new change having this:

```
{$IF CompilerVersion <= 15}
  if TMMinus.ClassInfo <> nil then
{$ENDIF CompilerVersion <= 15}
```

replaced by this:

```
{$IF CompilerVersion <= 15}
  if TMMinus.ClassInfo <> nil then
{$IFEND CompilerVersion <= 15}
```

Later on I will sort out how to get rid of the warning newer Delphi versions throw as they prefer `ENDIF`.

**Comment by hvassbotn** [comment]
Ok. I don't have D2007 here to test. You could replace it with IFDEF VER15, maybe. Do you need to support D2006 as well?

http://delphi.wikia.com/wiki/CompilerVersion_Constant

**Comment by jpluimers** [comment]
Changed to `<= 19` and added `Pass` in the form of `Check(True)` so it should work for any Delphi version supported by GExperts.

See fragment in https://github.com/jpluimers/HVRTTIUtils/commit/f4b21043f00d91fdae34f13fdd1296575bb51c0e :

```
{$IF CompilerVersion <= 19} // Delphi 2007 or older
  if TMMinus.ClassInfo = nil then
    Check(True) // pass
  else
{$IFEND CompilerVersion <= 19} // Delphi 2007 or older
```

**Comment by hvassbotn** [comment]
Good

**Pull request merged**
